/*
 * CreateNewProfile.java
 *
 * Created on 20.07.2013, 13:55:44
 */
package de.di.notify.gui;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Locale;
import java.util.Properties;
import java.util.ResourceBundle;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Emal Rahman
 */
public class CreateNewProfile extends javax.swing.JFrame {

    //"ReadBarcode", "ConvertTiff2Pdf", "SplitSortMerge"
    String actionList[] = {};
    
    private static ResourceBundle right_bundle;

    /**
     * Creates new form CreateNewProfile
     */
    public CreateNewProfile() {
        initComponents();
        loadResources();
    }

    public void loadResources() {
        BufferedImage image;
        ImageIcon icon;
        try {
            image = ImageIO.read(getClass().getResource("resources/favicon.png"));
            icon = new ImageIcon(image);
            this.setIconImage(icon.getImage());
        } catch (IOException ex) {
        }
        this.setLocation(200, 200);
        this.setSize(420, 220);
        this.setResizable(false);
        this.setAlwaysOnTop(true);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
        }
        SwingUtilities.updateComponentTreeUI(this);
        this.setLocation(500, 300);
        Locale locale = Locale.getDefault();
                
        try {            
            right_bundle = ResourceBundle.getBundle("notify/de/di/notify/gui/resources/CreateNewProfile", locale);
        } catch (Exception ex) {
            right_bundle = ResourceBundle.getBundle("contractmanager/de/di/notify/gui/resources/CreateNewProfile", locale);
        }
        
        ResourceBundle bundle = right_bundle; //ResourceBundle.getBundle("notify/de/di/notify/gui/resources/CreateNewProfile", locale);
        this.setTitle(bundle.getString("titel"));
        jLabel1.setText(bundle.getString("jLabel1.txt"));
        jLabel3.setText(bundle.getString("jLabel3.txt"));
        jLabel2.setText(bundle.getString("jLabel2.txt"));
        jButton1.setText(bundle.getString("jButton1.txt"));
        jButton2.setText(bundle.getString("jButton2.txt"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox(actionList);
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("jLabel2");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("jLabel3");
        jLabel3.setName("jLabel3"); // NOI18N

        jTextField1.setName("jTextField1"); // NOI18N

        jComboBox1.setName("jComboBox1"); // NOI18N

        jButton1.setText("jButton1");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, 211, Short.MAX_VALUE))
                        .addGap(71, 71, 71))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // suche nach identische ProfileName und Action
        // Fals eine vorliegt, abbrechen
        Properties prop = new Properties();
        boolean find = false;
        int numberOfProfile = new File("../profiles").list().length;
        String number = "";
        while (numberOfProfile >= 0) {
            number = Integer.toString(numberOfProfile);
            if (number.length() == 1) {
                number = "00" + number;
            } else if (number.length() == 2) {
                number = "0" + number;
            }
            try {
                prop.load(new FileInputStream("../profiles/profile_" + number + ".properties"));
            } catch (Exception ex) {
            }
            if (jTextField1.getText().equalsIgnoreCase(prop.getProperty("ProfileName"))
                    && jComboBox1.getSelectedItem().toString().equalsIgnoreCase(prop.getProperty("Action"))) {
                find = true;
                break;
            }
            numberOfProfile--;
        }
        if (find) {
            String errorMessage;
            if (System.getProperty("user.language").equalsIgnoreCase("de")) {
                errorMessage = "Ein Profil mit identischem Namen existiert bereits!";
            } else {
                errorMessage = "A profile with the same name already existing!";
            }
            JOptionPane.showMessageDialog(this, errorMessage);
            jTextField1.requestFocus();
        } else {

            // Erzeuge ein Profile_xxx.properties mit ProfileName und Aktion
            int newProfileNumber = Integer.valueOf(number);
            newProfileNumber++;
            number = String.valueOf(newProfileNumber);
            if (number.length() == 1) {
                number = "00" + number;
            } else if (number.length() == 2) {
                number = "0" + number;
            }
            try {
            // File newProfile = new File("../profiles/profile_" + number + ".properties");
                prop.load(new FileInputStream(new File("../profiles/profile_" + number + ".properties").getAbsolutePath()));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Cannot create new Profile : " + ex.getMessage());
            }
            prop.setProperty("ProfileName", jTextField1.getText());
            prop.setProperty("Action", jComboBox1.getSelectedItem().toString());
            prop.setProperty("SearchPages", "ALL");
            prop.setProperty("SearchArea", "Page");
            prop.setProperty("BC_0", "1");
            prop.setProperty("BC_90", "1");
            prop.setProperty("BC_180", "1");
            prop.setProperty("BC_270", "1");
            prop.setProperty("BC_SKEW_NONE", "1");
            prop.setProperty("Configuration1_ISSELECTED", "true");
            prop.setProperty("Configuration2_ISSELECTED", "true");
            prop.setProperty("Configuration3_ISSELECTED", "true");
            prop.setProperty("BC_LIGHTMARGIN", "30");
            prop.setProperty("BC_PERCENT", "100");
            prop.setProperty("BC_SCANDISTBAR", "3");
            prop.setProperty("BC_SCANDISTANCE", "15");
            prop.setProperty("BC_TOLERANCE", "20");
            prop.setProperty("BC_MAX_NO_VAL", "10");
            prop.setProperty("BC_MINHEIGHT", "15");
            prop.setProperty("BC_MAXHEIGHT", "400");
            
            
            

            // Selectiere die jList.select auf neue Profile und beende das CreateNewProfile.java                
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateNewProfile().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
